version: "3.4"
services:

# https://github.com/jupyter/docker-stacks/tree/master/all-spark-notebook
  jupyter: 
    image: 127.0.0.1:5001/jupyter
    build: /
#jupyter/
    ports:
      - 8888:8888
#    volumes:
#      - /mnt/il060-samba-share/jupyter_notebooks/testing:/home/jovyan/work/testing
#      - jupyterdata:/home/jovyan/work 
    networks:
      - datastore
    deploy:
      placement:
        constraints: [node.role == worker]
#      resources:
#        limits:
#          cpus: "1"
#          memory: 8G
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure



volumes:
  jupyterdata:
    driver: local

networks:
  datastore:



