version: "3.4"
services:
  grafana:
#    image: grafana/grafana:5.0.4
    image: 127.0.0.1:5001/grafana
    build: .
    ports:
      - 3000:3000
    volumes:
      -  /mnt/il060-samba-share/il08X/grafanadata:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      ELASTICSEARCH_ENDPOINT: http://elasticsearch:9200
#      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s/grafana/"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 3G
      replicas: 1
      placement:
        constraints: [node.role == worker]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
       condition: on-failure

