version: "3.4"
services:
  influxdb-grafana:
    image: philhawthorne/docker-influxdb-grafana:latest
    volumes:
      - ./influxdb:/var/lib/influxdb
      - ./grafana:/var/lib/grafana
    ports:
      - "3003:3003"
      - "3004:8083"
      - "8086:8086"
      - "22022:22"
