version: "3.4"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    volumes:
      - esdata:/usr/share/elasticsearch/data
#      - /mnt/glusterfs/dtz/datastack/elasticsearch/esbackup/:/usr/share/elasticsearch/backup
    configs:
      - source: esconfig
        target: /usr/share/elasticsearch/config/elasticsearch.yml
      - source: eslog4jconf
        target: /usr/share/elasticsearch/config/log4j2.properties
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    healthcheck:
      test: "exit 0"
      interval: 1m00s
      timeout: 10s
      retries: 3
    networks:
      - default
      - datastack
    deploy:
#      placement:
#        constraints: [node.role == worker]
      resources:
        limits:
          cpus: "3"
          memory: 6G
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.2.2
    configs:
      - source: lsconfig
        target: /usr/share/logstash/config/logstash.yml
#    volumes:
#      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - default
      - datastack
    depends_on:
      - elasticsearch
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
      replicas: 2
#      placement:
#        constraints: [node.role == worker]
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.2
    configs:
      - source: kibanaconfig
        target: /usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - default
      - datastack
    depends_on:
      - elasticsearch
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1G
      replicas: 1
#      placement:
#        constraints: [node.role == worker]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
       condition: on-failure

volumes:
  esdata:
    driver: local
  pipeline:
    driver: local

networks:
  datastack:
    driver: overlay
    attachable: true

configs:
  esconfig:
    file: elasticsearch/config/elasticsearch.yml
  eslog4jconf:
    file: elasticsearch/config/log4j2.properties
  kibanaconfig:
    file: kibana/config/kibana.yml
  lsconfig:
    file: logstash/config/logstash.yml
#  lspipeline:
#    file: logstash/pipeline/logstash.conf
